services:
  radicale:
    image: tomsquest/docker-radicale:latest
    container_name: radicale
    user: "1000:1000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    ports:
      - "5232:5232/tcp"
    volumes:
      - ./data/radicale-data:/data
      - ./data/radicale-config:/config:ro
      - ./data/radicale-certs:/certs:ro
    deploy:
      resources:
        limits:
          memory: 256M
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -k -f http://localhost:5232/.web/ || curl -k -f https://localhost:5232/.web/ || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: always
